### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [GarrettLee/label_noise_correction#1]
Hello Lee,

Thanks for your job. Could you please add the readme on this repository, something like how to run and organization of the repository? Thanks.

Zhihao

**Comment by GarrettLee** [comment]
Hi ZHAOZHIHAO,

I was planning to use this repo for storing my codes, and haven't thought of sharing this with others. So I am surprised that you are interested in it.  I am not working on this repo recently, but I will add a simple readme for it when I have free time.

Lee

**Comment by GarrettLee** [comment]
A readme has been added.

**Comment by ZHAOZHIHAO** [comment]
Hi Lee,

Thank you very much for spending your precious time on that.

Zhihao
